from build import *
data=json.loads((R/'manifest.json').read_text());data['labels']=LABELS
html=r'''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>위저드 · 모션 검토</title><style>
*{box-sizing:border-box}body{margin:0;background:#131e29;color:#eee8dc;font:16px system-ui,sans-serif}main{max-width:1180px;margin:auto;padding:32px}h1{font-size:28px;margin:0 0 8px}p{color:#bfc8d1;line-height:1.6}button,select{font:inherit;background:#2b3a4b;color:#fff;border:1px solid #5b6b7b;border-radius:8px;padding:10px;margin:4px}button{cursor:pointer}img,canvas{image-rendering:pixelated}canvas{background:#24313d;max-width:100%;height:auto}section{background:#1d2b39;border:1px solid #334758;border-radius:12px;padding:20px;margin:20px 0}.stage{display:flex;gap:16px;align-items:start;flex-wrap:wrap}.view{flex:1;min-width:256px}a{color:#9dd4dc}.strip{display:flex;overflow-x:auto;gap:8px}.frame{background:#24313d;border:2px solid transparent;flex:none}.frame.on{border-color:#dfbd74}.frame img{width:256px;display:block}.frame p{margin:4px 10px;font-size:12px}#compare{width:100%}#meta{min-height:52px}.sub{font-size:13px}.legend{display:grid;grid-template-columns:repeat(3,1fr);text-align:center;color:#e8cf96}</style><main>
<h1>위저드 · 기본 동작과 스킬</h1><p>여성 위저드 / 지팡이 · 기본 8종 · 스킬 모션 10종 / 28개 스킬</p>
<section><div class="legend"><span>쿠키 r12</span><span>기사 r15</span><span>위저드</span></div><img id="compare" src="comparison_4x.png" alt="같은 배율의 쿠키 기사 위저드"><p class="sub">128×120 캔버스 · 대기 키 48px · 발 기준 (64,112) · 동일 배율 비교</p></section>
<section><label>동작 <select id="motion"></select></label><button id="play">일시정지</button><button id="prev">이전 장</button><button id="next">다음 장</button><button id="restart">처음부터</button><label><input id="repeat" type="checkbox" checked>검토 반복</label><p id="meta"></p><div class="stage"><div class="view"><canvas id="view" width="512" height="480"></canvas></div><div class="view"><p id="against">일반 공격 / 선택한 스킬 (왼쪽 / 오른쪽)</p><img id="pair" style="width:100%"><p><a id="gif1">1× GIF</a> · <a id="gif4">4× GIF</a> · <a id="sheet">프레임 시트</a></p><p class="sub">공격성 스킬의 타격 전 구간은 130ms. 자기 버프에는 타격 프레임이 없습니다. 마법 이펙트는 게임에서 별도로 표시합니다.</p><p><a href="NOTES.md">제작 기록</a> · <a href="manifest.json">매니페스트</a> · <a href="verification/validation.json">검증 결과</a></p></div></div><div id="strip" class="strip"></div></section>
<section><h2>시전 연결</h2><p>손 모으기 → 시전 유지. 시작은 한 번 재생하고 유지 동작은 반복합니다.</p><img src="cast_start_4x.gif" width="384"><img src="cast_4x.gif" width="384"></section></main><script>
const DATA=__DATA__, A=DATA.characters.wizard_female_p2.animations, labels=DATA.labels, mappings=DATA.characters.wizard_female_p2.skillMotions;
const $=id=>document.getElementById(id),ctx=$('view').getContext('2d');ctx.imageSmoothingEnabled=false;
let name='idle',index=0,running=true,elapsed=0,last=0,imgs={};
for(const f of Object.values(A).flatMap(a=>a.frames)){const im=new Image;im.src='composite/'+f+'.png';imgs[f]=im;}
for(const n of Object.keys(A)){const o=new Option(labels[n]+' · '+n,n);$('motion').add(o)}
function show(){let a=A[name];ctx.clearRect(0,0,512,480);let im=imgs[a.frames[index]];if(im.complete)ctx.drawImage(im,0,0,512,480);document.querySelectorAll('.frame').forEach((el,i)=>el.classList.toggle('on',i===index));$('meta').textContent=`${labels[name]} · ${index+1}/${a.frames.length}장 · ${a.durations[index]}ms · 전체 ${a.duration}ms`+(a.hitFrame===undefined?'':` · 타격 ${a.hitFrame+1}번째 장`)+(Object.entries(mappings).filter(([s,m])=>m===name).map(([s])=>s).length?'\n'+Object.entries(mappings).filter(([s,m])=>m===name).map(([s])=>s).join(', '):'');}
function change(n){name=n;index=0;elapsed=0;$('strip').innerHTML='';A[n].frames.forEach((f,i)=>{const el=document.createElement('div');el.className='frame';el.innerHTML=`<img src="composite/${f}.png"><p>${i+1}장 · ${A[n].durations[i]}ms${A[n].hitFrame===i?' · 타격':''}</p>`;el.onclick=()=>{running=false;index=i;elapsed=0;show();$('play').textContent='재생'};$('strip').append(el)});$('pair').src=n.startsWith('skill_')?'attack_vs_'+n+'_4x.gif':'attack_4x.gif';$('against').textContent=n.startsWith('skill_')?'일반 공격 / 선택한 스킬 (왼쪽 / 오른쪽)':'일반 공격 참고';$('gif1').href=n+'_1x.gif';$('gif4').href=n+'_4x.gif';$('sheet').href=n+'_contact_sheet.png';show();}
$('motion').onchange=e=>change(e.target.value);$('play').onclick=()=>{running=!running;$('play').textContent=running?'일시정지':'재생'};for(let [id,step] of [['prev',-1],['next',1]])$(id).onclick=()=>{running=false;$('play').textContent='재생';index=(index+step+A[name].frames.length)%A[name].frames.length;elapsed=0;show()};$('restart').onclick=()=>{index=0;elapsed=0;running=true;$('play').textContent='일시정지'};
function tick(t){if(last&&running){elapsed+=Math.min(t-last,100);let a=A[name];while(elapsed>=a.durations[index]){elapsed-=a.durations[index];if(index<a.frames.length-1)index++;else if(a.loop||$('repeat').checked)index=0;else{running=false;elapsed=0;$('play').textContent='재생';break}}}last=t;show();requestAnimationFrame(tick)}change('idle');requestAnimationFrame(tick);
</script></html>'''
(R/'preview.html').write_text(html.replace('__DATA__',json.dumps(data,ensure_ascii=False)))
print('preview.html ready')
