from pathlib import Path
import json
R=Path(__file__).resolve().parent
m=json.loads((R/'manifest.json').read_text());c=m['characters']['assassin_male_p2']
labels={'idle':'대기','walk':'걷기','attack':'일반 공격','hurt':'피격','dead':'쓰러짐','sit':'앉기','cast':'시전','skill_sonic':'음속 연격','skill_grimtooth':'그림자 송곳니','skill_envenom':'맹독','skill_scatter':'모래·독 안개 뿌리기','skill_throw':'돌·독 단검 던지기','skill_pickup':'돌 줍기','skill_plant':'독 폭탄 심기','skill_coat':'맹독 부여','skill_guard':'독 반격','skill_detox':'해독','skill_hide':'하이딩·은신 이동','skill_backslide':'뒤로 구르기'}
html='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>어쌔신 · 기본 동작과 스킬 검토</title>
<style>
:root{color-scheme:dark;font-family:system-ui,sans-serif;background:#101820;color:#f2e8d6}*{box-sizing:border-box}body{max-width:1160px;margin:32px auto;padding:0 24px}h1{font-size:30px;margin-bottom:8px}h2{font-size:19px}p{color:#b9c5d0;line-height:1.6}small{color:#abb8c6}a{color:#ead08c}button,select{font:inherit;border:1px solid #586071;background:#283342;color:#f4ead7;border-radius:6px;padding:9px 14px;cursor:pointer}button:hover,button.active{background:#66516c;border-color:#d7b6de}button:focus-visible,select:focus-visible,input:focus-visible{outline:3px solid #efca7f}nav,.controls{display:flex;gap:8px;flex-wrap:wrap;margin:16px 0}.panel{border:1px solid #384756;border-radius:12px;background:#1b2632;padding:18px;margin:20px 0}.pair{display:grid;grid-template-columns:1fr 1fr;gap:18px}.stage{overflow:auto;background:#25313e;border:1px solid #3e4e5e;border-radius:8px;text-align:center}.stage canvas{display:block;image-rendering:pixelated;margin:auto;max-width:100%;height:auto}.caption{color:#dec48f;display:block;padding:8px}#status{min-height:26px;font-variant-numeric:tabular-nums}input[type=range]{width:100%}.sheet{max-width:100%;image-rendering:pixelated}.styleLabels{display:grid;grid-template-columns:repeat(3,1fr);text-align:center;color:#d5bd91}table{width:100%;border-collapse:collapse;font-size:14px}td,th{text-align:left;border-bottom:1px solid #3b4856;padding:10px 6px}code{font-size:12px;color:#caadce}.meta{display:flex;gap:18px;flex-wrap:wrap}#frameList{display:flex;gap:6px;flex-wrap:wrap}#frameList button{font-size:12px;padding:6px 9px}#load{color:#dac080}@media(max-width:680px){.pair{grid-template-columns:1fr}body{padding:0 12px}table{font-size:12px}}
</style><h1>어쌔신</h1><p>남성 · 2등신 · 카타르 / 단검<br>기본 동작 7종과 스킬 동작 12종 · 게임 스킬 15개 연결</p>
<p><a href="NOTES.md">제작 기록</a> · <a href="manifest.json">매니페스트</a> · <a href="verification/validation.json">검증 결과</a></p><div id="load">이미지 읽는 중…</div>
<nav id="actions" aria-label="동작 선택"></nav><div class="panel"><div class="controls"><label>무기 <select id="weapon"><option value="katar">카타르</option><option value="dagger">단검</option></select></label><label>크기 <select id="scale"><option value="4">4×</option><option value="1">1×</option></select></label><label>재생 속도 <select id="speed"><option value="1">정상</option><option value="0.25">¼ 속도</option></select></label><button id="play">일시정지</button><button id="prev">이전 장</button><button id="next">다음 장</button><button id="restart">처음부터</button></div>
<div class="pair"><div class="stage"><span class="caption">일반 공격</span><canvas id="left" width="128" height="72"></canvas></div><div class="stage"><span class="caption" id="selected">대기</span><canvas id="right" width="128" height="72"></canvas></div></div><p id="status" aria-live="off"></p><input id="scrub" type="range" min="0" value="0" aria-label="프레임"><div id="frameList"></div><p id="details"></p><div class="meta"><a id="gif1" href="idle_1x.gif">1× GIF</a><a id="gif4" href="idle_4x.gif">4× GIF</a><a id="sheetLink" href="idle_contact_sheet.png">동작 시트</a></div></div>
<div class="panel"><h2>같은 발 기준점 · 같은 배율</h2><div class="styleLabels"><span>쿠키 r12</span><span>기사 r15</span><span>어쌔신</span></div><img class="sheet" src="size_comparison_4x.png" alt="쿠키, 기사, 어쌔신 크기 비교"><p>128×120 캔버스 · 발 기준 (64,112) · 대기 기본 키 48px. 화면 재생 영역은 위쪽 여백만 잘라 표시합니다.</p></div>
<div class="panel"><h2>스킬 연결</h2><table><thead><tr><th>스킬 ID</th><th>동작</th><th>타격 시작 / 길이</th></tr></thead><tbody id="mapping"></tbody></table></div><details class="panel"><summary>기본 동작 전체 시트</summary><img class="sheet" src="contact_sheet.png" alt="기본 동작 30프레임"></details><details class="panel"><summary>스킬 전체 시트</summary><img class="sheet" src="skills_contact_sheet.png" alt="스킬 81프레임"></details><p>원화 45개를 채택하고 준비·회수·정착 자세를 공유했습니다. 111개 프레임 항목이 모두 별개의 신규 원화인 것은 아닙니다. 게임 적용 전 검토용 패키지입니다.</p>
<script>
const C=__CHAR__,L=__LABELS__, cache={};
const $=id=>document.getElementById(id);
let action='idle',frame=0,playing=true,time=0,last=0;
const A=C.animations;
function pick(a,t){let z=0;for(let i=0;i<a.frames.length;i++){z+=a.durations[i];if(t<z)return i}return a.frames.length-1}
function draw(canvas,n){const ctx=canvas.getContext('2d');ctx.imageSmoothingEnabled=false;ctx.fillStyle='#25313e';ctx.fillRect(0,0,128,72);ctx.strokeStyle='#41505e';ctx.beginPath();ctx.moveTo(0,64.5);ctx.lineTo(128,64.5);ctx.stroke();const im=cache[$('weapon').value+'/'+n];if(im)ctx.drawImage(im,0,48,128,72,0,0,128,72);let s=Number($('scale').value);canvas.style.width=128*s+'px';canvas.style.height=72*s+'px'}
function render(){const a=A[action],attack=A.attack;const at=Math.min(time,attack.duration-1);draw($('left'),attack.frames[pick(attack,at)]);draw($('right'),a.frames[frame]);$('status').textContent=L[action]+' · '+(frame+1)+' / '+a.frames.length+'장 · '+a.durations[frame]+'ms'+(frame===a.hitFrame?' · 타격 / 방출':'');$('scrub').value=frame;$('play').textContent=playing?'일시정지':'재생';document.querySelectorAll('#frameList button').forEach((b,i)=>b.classList.toggle('active',i===frame))}
function seek(i){playing=false;frame=Math.max(0,Math.min(A[action].frames.length-1,i));time=A[action].durations.slice(0,frame).reduce((a,b)=>a+b,0);render()}
function select(n){action=n;frame=0;time=0;const a=A[n];$('selected').textContent=L[n];$('scrub').max=a.frames.length-1;$('details').textContent=a.duration+'ms · '+('hitFrame'in a?'타격 프레임 '+a.hitFrame+' / 시작 '+a.durations.slice(0,a.hitFrame).reduce((p,q)=>p+q,0)+'ms':'타격 판정 없음')+(a.holdLast?' · 마지막 자세 유지':'')+' · 비교 재생은 매 회 시작을 맞춥니다.';$('gif1').href=n+'_1x.gif';$('gif4').href=n+'_4x.gif';$('sheetLink').href=n+'_contact_sheet.png';$('frameList').replaceChildren();a.frames.forEach((f,i)=>{let b=document.createElement('button');b.textContent=i+' · '+a.durations[i];b.onclick=()=>seek(i);$('frameList').append(b)});document.querySelectorAll('#actions button').forEach(b=>b.classList.toggle('active',b.dataset.action===n));render()}
for(const n of Object.keys(A)){let b=document.createElement('button');b.textContent=L[n];b.dataset.action=n;b.onclick=()=>select(n);$('actions').append(b)}
for(const [id,n] of Object.entries(C.skillMotions)){const a=A[n],tr=document.createElement('tr');tr.innerHTML='<td><code>'+id+'</code></td><td><button>'+L[n]+'</button></td><td>'+('hitFrame'in a?'130ms':'없음')+' / '+a.duration+'ms</td>';tr.querySelector('button').onclick=()=>{select(n);window.scrollTo({top:0,behavior:'smooth'})};$('mapping').append(tr)}
$('play').onclick=()=>{playing=!playing;render()};$('prev').onclick=()=>seek(frame-1);$('next').onclick=()=>seek(frame+1);$('restart').onclick=()=>{time=0;frame=0;playing=true;render()};$('scrub').oninput=()=>seek(Number($('scrub').value));$('weapon').onchange=render;$('scale').onchange=render;
function tick(now){if(last&&playing){const a=A[action];time+=(now-last)*Number($('speed').value);const duration=Math.max(a.duration,A.attack.duration)+250;if(time>=duration)time=0;frame=pick(a,time);render()}last=now;requestAnimationFrame(tick)}
Promise.all(Object.keys(C.frames).flatMap(n=>['katar','dagger'].map(w=>new Promise((resolve,reject)=>{const im=new Image;im.onload=()=>{cache[w+'/'+n]=im;resolve()};im.onerror=()=>reject(new Error(n));im.src='composite/'+(w==='dagger'?'dagger/':'')+n+'.png'})))).then(()=>{$('load').textContent='222개 합성 이미지 읽기 완료';select('idle');requestAnimationFrame(tick)}).catch(e=>{$('load').textContent='이미지를 읽지 못했습니다: '+e.message});
</script></html>'''
(R/'preview.html').write_text(html.replace('__CHAR__',json.dumps(c,ensure_ascii=False)).replace('__LABELS__',json.dumps(labels,ensure_ascii=False)))
print('preview.html written')
