from build import *
m=json.loads((R/'manifest.json').read_text())
template='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>프리스트 · 기본 동작과 스킬 검토</title><style>
*{box-sizing:border-box}body{margin:0;background:#17212b;color:#eee9dc;font:16px/1.65 system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:32px}h1{margin:0;font-size:30px}p{color:#b8c7ca}button,select,a{font:inherit}button,select{background:#344552;border:1px solid #697d86;border-radius:7px;color:#fff;padding:8px 14px;cursor:pointer}button:hover{background:#4b6070}a{color:#f2d395}section{margin:24px 0;background:#24313d;padding:22px;border-radius:12px}img,canvas{image-rendering:pixelated}canvas{background:#24313d;max-width:100%;height:auto}#controls{display:flex;gap:10px;flex-wrap:wrap;align-items:center}#info{min-height:48px;color:#ffda94}.scroll{overflow:auto}.sheet{max-width:none;height:240px}#pair{width:768px;max-width:100%;height:auto}.comparison{width:100%;max-width:1152px;height:auto}table{border-collapse:collapse;width:100%}td,th{text-align:left;padding:9px;border-bottom:1px solid #465561}small{color:#a8b7be}.links{display:flex;gap:18px;flex-wrap:wrap}.tiny{width:384px;max-width:100%}</style><main>
<h1>프리스트</h1><p>상아색 왕관 땋은 머리 · 자주색 예복 · 철퇴<br>기본 8종 / 스킬 모션 13종 / 스킬 32개 · 걷기와 공격 8장</p>
<section><div id="controls"><select id="motion" aria-label="동작 선택"></select><button id="play">일시정지</button><button id="prev">이전 장</button><button id="next">다음 장</button><label><input id="repeat" type="checkbox" checked> 반복 검토</label></div><canvas id="stage" width="512" height="480" aria-label="프리스트 애니메이션"></canvas><div id="info"></div><div class="links"><a id="gif1">GIF 1×</a><a id="gif4">GIF 4×</a><a id="contact">동작 시트</a></div><div class="scroll"><img class="sheet" id="strip" alt="선택 동작 프레임 시트"></div></section>
<section><h2>기준 캐릭터와 크기 비교</h2><p>왼쪽부터 쿠키 r12 · 기사 r15 · 프리스트. 같은 발 기준점, 대기 키 48px.</p><img class="comparison" src="comparison_4x.png" alt="쿠키 기사 프리스트 4배 비교"><div><img class="tiny" src="comparison_1x.png" alt="원본 크기 비교"></div></section>
<section id="compare"><h2>일반 공격 ↔ 선택 스킬</h2><p>왼쪽 일반 공격 · 오른쪽 선택 스킬. 같은 시작 시각, 짧은 쪽은 마지막 장 유지.</p><img id="pair" alt="일반 공격과 스킬 비교"></section>
<section><h2>스킬 배정</h2><table><thead><tr><th>모션</th><th>스킬 ID</th></tr></thead><tbody id="mapping"></tbody></table></section><div class="links"><a href="skills_contact_sheet.png">전체 스킬 시트</a><a href="contact_sheet.png">전체 110프레임</a><a href="NOTES.md">제작 기록</a><a href="manifest.json">매니페스트</a></div><p><small>공격·주문 이펙트는 게임 담당. 이 패키지에는 몸 동작과 철퇴 잔상만 포함합니다. 파일을 직접 열어 사용할 수 있습니다.</small></p></main><script>
const data=__MANIFEST__,labels=__LABELS__,groups=__GROUPS__;
const animations=data.characters.priest_female_p2.animations;
const $=id=>document.getElementById(id),select=$('motion'),ctx=$('stage').getContext('2d');ctx.imageSmoothingEnabled=false;
let name='walk',index=0,playing=true,last=0,elapsed=0;const cache={};
for(const [key,a] of Object.entries(animations)){const opt=document.createElement('option');opt.value=key;opt.textContent=labels[key]+' · '+key;select.append(opt);for(const frame of a.frames){const im=new Image;im.src='composite/'+frame+'.png';cache[frame]=im;}}
for(const [key,ids] of Object.entries(groups)){const tr=document.createElement('tr'),a=document.createElement('td'),b=document.createElement('td');const btn=document.createElement('button');btn.textContent=labels[key];btn.onclick=()=>choose(key);a.append(btn);b.textContent=ids.join(', ');tr.append(a,b);$('mapping').append(tr);}
function choose(n){name=n;select.value=n;index=0;elapsed=0;last=0;for(const s of [1,4])$('gif'+s).href=n+'_'+s+'x.gif';$('contact').href=n+'_contact_sheet.png';$('strip').src=n+'_contact_sheet.png';$('compare').hidden=!n.startsWith('skill_');if(n.startsWith('skill_'))$('pair').src='attack_vs_'+n+'_4x.gif';paint();}
function paint(){const a=animations[name];ctx.clearRect(0,0,512,480);const im=cache[a.frames[index]];if(im.complete&&im.naturalWidth)ctx.drawImage(im,0,0,512,480);$('info').textContent=labels[name]+' · '+index+' / '+(a.frames.length-1)+' · '+a.durations[index]+' ms · 총 '+a.duration+' ms'+(a.hitFrame===undefined?' · 타격 프레임 없음':' · 효과 장 '+a.hitFrame+(index===a.hitFrame?' [현재]':''));}
$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'일시정지':'재생';last=0;};
function step(d){playing=false;$('play').textContent='재생';index=(index+d+animations[name].frames.length)%animations[name].frames.length;elapsed=0;paint();}
$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);select.onchange=()=>choose(select.value);
function tick(t){const a=animations[name];if(playing&&last){elapsed+=Math.min(t-last,200);while(elapsed>=a.durations[index]){elapsed-=a.durations[index];if(index<a.frames.length-1)index++;else if($('repeat').checked||a.loop)index=0;else{playing=false;$('play').textContent='재생';break;}}}last=t;paint();requestAnimationFrame(tick);}choose(name);requestAnimationFrame(tick);
</script></html>'''
(R/'preview.html').write_text(template.replace('__MANIFEST__',json.dumps(m,ensure_ascii=False)).replace('__LABELS__',json.dumps(LABELS,ensure_ascii=False)).replace('__GROUPS__',json.dumps(GROUPS)),encoding='utf-8')
