from pathlib import Path
import json
R=Path(__file__).resolve().parent
m=json.loads((R/'manifest.json').read_text());c=m['characters']['hunter_male_p2']
labels=dict(zip(c['animations'],['대기','걷기','일반 사격','피격','쓰러짐','앉기','시전 유지','이중 사격','화살비','강한·환영 사격','집중','매 지시','탐지','호각','덫 설치']))
html='''<!doctype html><html lang="ko"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>헌터 · 기본 동작과 스킬 검토</title>
<style>body{background:#17232e;color:#f4efdf;font:16px system-ui;max-width:1100px;margin:40px auto;padding:20px}h1{margin-bottom:8px}p{color:#bbcab8;line-height:1.6}img,canvas{image-rendering:pixelated}button,select{font:inherit;background:#2f453e;color:#fff;border:1px solid #6c8b76;border-radius:5px;padding:9px;margin:4px}#stage{display:flex;align-items:end;gap:30px;background:#24313d}#native{width:128px;height:120px}#big{width:512px;height:480px}#compare{max-width:100%}#strip{display:flex;overflow:auto;background:#24313d}figure{margin:10px;text-align:center;white-space:nowrap}figure img{width:256px;height:240px}a{color:#f0d490}.size{width:100%;max-width:1100px}</style>
<h1>헌터 · 기본 동작과 스킬</h1><p>남성 헌터 / 활 · 기본 7종 · 스킬 모션 8종 / 18개 스킬<br>쿠키 · 기사 · 헌터 — 동일 배율 비교</p><img class="size" src="comparison_4x.png" alt="쿠키 기사 헌터 크기 비교"><p>128×120 · 대기 키 48px · 발 기준 (64,112)</p>
<label>동작 <select id="motion"></select></label><button id="play">일시정지</button><button id="prev">이전 장</button><button id="next">다음 장</button><button id="restart">처음부터</button><label><input type="checkbox" id="loop" checked>검토 반복</label>
<div id="stage"><canvas id="native" width="128" height="120"></canvas><canvas id="big" width="128" height="120"></canvas></div><p id="info"></p><p id="mapping"></p><p><a id="one">1× GIF</a> · <a id="four">4× GIF</a> · <a id="sheet">프레임 시트</a></p><div id="strip"></div><h2>일반 사격 / 선택 스킬</h2><img id="compare" alt="일반 사격과 선택 스킬 비교"><p>스킬 타격·설치·매 지시 프레임은 시작 130ms. 집중·탐지·호각에는 타격 프레임이 없습니다.<br>매, 덫, 비행 화살과 이펙트는 게임에서 별도로 표시합니다.</p><p><a href="NOTES.md">제작 기록</a> · <a href="manifest.json">매니페스트</a> · <a href="verification/validation.json">검증 결과</a></p>
<script>const C=CHARACTER,L=LABELS,A=C.animations;let name='idle',index=0,playing=true,last=0,elapsed=0;const images={};for(const n in C.frames){const im=new Image();im.src='composite/'+n+'.png';im.onload=draw;images[n]=im}const $=id=>document.getElementById(id);for(const n in A){const o=document.createElement('option');o.value=n;o.textContent=L[n]+' · '+n;$('motion').append(o)}
function draw(){let a=A[name],im=images[a.frames[index]];for(const id of ['native','big']){const x=$(id).getContext('2d');x.imageSmoothingEnabled=false;x.fillStyle='#24313d';x.fillRect(0,0,128,120);if(im?.complete)x.drawImage(im,0,0)}$('info').textContent=L[name]+' · '+(index+1)+'/'+a.frames.length+'장 · '+a.durations[index]+'ms · 전체 '+a.duration+'ms'+(a.hitFrame!=null?' · 타격 '+(a.hitFrame+1)+'번째 장':'');}
function choose(){name=$('motion').value;index=0;elapsed=0;for(const [id,s]of [['one','1x.gif'],['four','4x.gif'],['sheet','contact_sheet.png']])$(id).href=name+'_'+s;$('mapping').textContent=Object.keys(C.skillMotions).filter(k=>C.skillMotions[k]===name).join(' · ');$('compare').src=name.startsWith('skill_')?'attack_vs_'+name+'_4x.gif':'attack_4x.gif';$('strip').replaceChildren();A[name].frames.forEach((n,i)=>{const f=document.createElement('figure'),im=new Image(),cap=document.createElement('figcaption');im.src='composite/'+n+'.png';cap.textContent=(i+1)+'장 · '+A[name].durations[i]+'ms'+(i===A[name].hitFrame?' · 타격':'');f.append(im,cap);$('strip').append(f)});draw()}
$('motion').onchange=choose;$('play').onclick=()=>{playing=!playing;$('play').textContent=playing?'일시정지':'재생'};function step(d){playing=false;$('play').textContent='재생';index=(index+d+A[name].frames.length)%A[name].frames.length;elapsed=0;draw()}$('prev').onclick=()=>step(-1);$('next').onclick=()=>step(1);$('restart').onclick=()=>{index=0;elapsed=0;draw()};function tick(t){if(playing){elapsed+=Math.min(t-last,100);while(elapsed>=A[name].durations[index]){elapsed-=A[name].durations[index];if(index+1<A[name].frames.length)index++;else if($('loop').checked)index=0;else{playing=false;break}}draw()}last=t;requestAnimationFrame(tick)}choose();requestAnimationFrame(tick);</script></html>'''
(R/'preview.html').write_text(html.replace('CHARACTER',json.dumps(c,ensure_ascii=False)).replace('LABELS',json.dumps(labels,ensure_ascii=False)))
